version: '3'

services:
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    build:
      context: ./backend
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
