version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3020:3020"
    env_file:
      - ./frontend/.env.local

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env.local
    depends_on:
      - frontend