version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3020:3020"
    env_file:
      - ./frontend//Users/margothuet/Desktop/RNCP/Dossier projet/quantumcamp-webapp/frontend/.env.production

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend//Users/margothuet/Desktop/RNCP/Dossier projet/quantumcamp-webapp/backend/.env.production
    depends_on:
      - frontend