name: CD Workflow

on:
  push:
    branches: 
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: 188.165.238.74
          username: debian
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            /home/debian/QuantumCamp/quantumcamp-webapp
            docker-compose -f docker-compose.yaml build
            docker-compose -f docker-compose.yaml up -d
